Add inst scientist auth
fiaisis/fia-auth pull request #92
Opened 2024-12-18 11:52 UTC by Pasarus

Closes #30

## Description
Allow instrument scientists to log in and perform operations without being added manually.

2025-01-06 11:30 UTC, keiranjprice101 requested changes
2 minotr things

2025-01-06 11:30 UTC, keiranjprice101 commented on fia_auth/roles.py
> +    uows_url = os.environ.get("UOWS_URL", "https://devapi.facilities.rl.ac.uk/users-service")
Can you add a docstring

2025-01-06 11:30 UTC, keiranjprice101 commented on fia_auth/roles.py
> +        logger.info("User number %s is not an instrument scientist or UOWS API is down", user_number)
Is this true? e.g. if the UOWS is not down but they do not have the instrument scientist role, wont the response still have an 200 status? 

I only raise it to avoid potential future confusion

2025-01-06 16:13 UTC, Dagonite approved these changes

2025-01-09 09:23 UTC, keiranjprice101 approved these changes

2025-01-09 09:26 UTC, merged